### PR TITLE
http_server: log client disconnections

### PR DESCRIPTION
**Pull request by sirupsen**
Log when clients disconnect to get a sense of https://github.com/Shopify/undercloud/issues/40 (I know this is not an open issue, unlike this one, but eh) if we disable `Unicorn::Configurator.check_client_connection`. I don't expect much of this when `check_client_connection` is enabled, so I think dumping the `ENV` for debugging is fine. I don't really want to selectively choose values before I understand the patterns better. My plan is to try to disable `#check_client_connection` on some hosts.

@Shopify/undercloud @csfrancis @shivnagarajan

### CODE REVIEW

**Comment by sirupsen** [comment]
yep, I still need to figure out how to run the test suite—but this seems useful for solving the issue above

**Comment by kirs** [comment]
@sirupsen great work! When do you plan to 🚢  it? Do you want me to look into running the CI?

**Comment by sirupsen** [comment]
I'm going to do this along with https://github.com/Shopify/undercloud/issues/40

I don't think we need CI, should be OK to run locally. Thanks though!

**Comment by sirupsen** [comment]
In master with https://github.com/Shopify/unicorn/commit/dee503971ab258d36dc25db8a908dea3990d701d

**Pull request closed without merging**
